apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: webportal
  labels:
    app.kubernetes.io/name: webportal
spec:
  minReplicas: 1
  maxReplicas: 1
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 95
        type: Utilization
    type: Resource
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: webportal
    