# https://kubernetes.io/docs/tasks/manage-kubernetes-objects/kustomization/#bases-and-overlays
# Run `kubectl kustomize ./base` to see what manifest files will be generated
resources:
- service.yaml
- deployment.yaml
- ingress.yaml
- hpa.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
